### PR TITLE
Proper Size Founded:)

### PR DESCRIPTION
**Pull request by saeedark**
114*57
is the size
and 5 picture have been taken in different time .
maybe less than .4 ms

### CODE REVIEW

**Comment by kenny3794** [comment]
saeedark - I just installed your branch of libfprint with 0.7, 0.8 and 0.9 fprintd.  When I run fprintd-enroll, the device is recognized but then doesn't respond to any fingerprint scans.  What am I missing?

**Comment by indev29** [comment]
This branch is just a result of someone's R&D - there are no changes affecting  fingerprint recognition  thus nothing to make it actually work.

**Comment by kenny3794** [comment]
Thanks. TBH, when I saw this merge request I thought it was an indication that the driver was nearing ready. I see now I should have read more before asking.  I have more questions on porting this driver over to libfprint 2 in development and making it usable.  Should I ask here or via email?

**Comment by indev29** [comment]
Just email me if you have any questions

**Comment by coder3101** [comment]
Recently another device etes603 got merged in libfprint, it is from same vendor so I thought maybe you can re use some of their works in designing the algorithm for fingerprint matching.

https://github.com/patrickmarlier/etes603-dev

**Comment by indev29** [comment]
I'll try to look into it, thanks.

**Pull request merged**
